---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liquanhui.
--- DateTime: 2023/9/3 19:26
---
val = redis.call("GET", KEYS[1])
if val == false then
    -- 标识没有获取到数据，锁不存在
    return redis.call("SET", KEYS[1], ARGV[1], 'EX', ARGV[2])
elseif val == ARGV[1] then
    -- 上次加锁成功了，直接续约即可
    redis.call("EXPIRE", KEYS[1], ARGV[2])
    return "OK"
else
    return ""
end