---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liquanhui.
--- DateTime: 2023/9/3 14:56
---
--- 先查询锁是否存在，如果存在则过期时间加一分钟
if redis.call("GET", KEYS[1]) == ARGV[1] then
    return redis.call("EXPIRE", KEYS[1], ARGV[2])
else
    return 0
end