---
--- Generated by Luanalysis
--- Created by liquanhui.
--- DateTime: 2023/9/3 10:27
---
-- 尝试获取redis中的数据，并比对值
if redis.call("GET", KEYS[1]) == ARGV[1] then
    return redis.call("DEL", KEYS[1])
else
    return 0
end
